In [1]:
import pandas as pd
import json

with open('questao_5.json', 'r') as file:
    data = json.load(file)
df = pd.json_normalize(data, sep='_')
df

,id_pedido,data_pedido,status,cliente_id_cliente,cliente_nome_cliente,compra_id_produto,compra_nome_produto,compra_categoria,compra_quantidade,compra_preco_unitario,compra_preco_total
0,26,2025-01-26,Entregue,126,Zeca Costa,226,Cadeira de EscritÃ³rio,MÃ³veis,1,550.0,550.0
1,27,2025-01-27,Pendente,127,Amanda Melo,227,Colar de Prata,AcessÃ³rios,1,120.0,120.0
2,28,2025-01-28,Entregue,128,Bruna Santos,228,FogÃ£o 4 Bocas,EletrodomÃ©sticos,1,1200.0,1200.0
3,29,2025-01-29,Cancelado,129,Carlos Silva,229,Geladeira,EletrodomÃ©sticos,1,3500.0,3500.0
4,30,2025-01-30,Entregue,130,DÃ©bora Lima,230,Teclado MecÃ¢nico,EletrÃ´nicos,1,300.0,300.0